### ISSUE TITLE
Provisioning with example Vagrantfile fails

### ISSUE THREAD

**Issue by jhoblitt** [gds-operations/puppet-graphite#29] opened 2014-08-29 17:33 UTC
```
warning: Could not retrieve fact fqdn
warning: Host is missing hostname and/or domain: graphite
info: Applying configuration version '1409333312'
notice: /Stage[main]/Graphite::Deps/Package[python-cairo]/ensure: ensure changed 'purged' to 'present'
notice: /Stage[main]/Python::Install/Package[python-pip]/ensure: ensure changed 'purged' to 'present'
notice: /Stage[main]/Python::Install/Package[python-virtualenv]/ensure: ensure changed 'purged' to 'present'
notice: /Stage[main]/Python::Install/Package[python-dev]/ensure: ensure changed 'purged' to 'present'
notice: /Stage[main]/Graphite::Deps/Python::Virtualenv[/var/lib/graphite]/File[/var/lib/graphite]/ensure: created
notice: /Stage[main]/Graphite::Deps/Python::Virtualenv[/var/lib/graphite]/Exec[python_virtualenv_/var/lib/graphite]/returns: executed successfully
notice: /Stage[main]/Graphite::Deps/Python::Pip[twisted==11.1.0]/Exec[pip_install_twisted==11.1.0]/returns: executed successfully
notice: /Stage[main]/Graphite::Deps/Python::Pip[python-memcached==1.47]/Exec[pip_install_python-memcached==1.47]/returns: executed successfully
notice: /Stage[main]/Graphite::Deps/Python::Pip[django==1.4.10]/Exec[pip_install_django==1.4.10]/returns: executed successfully
notice: /Stage[main]/Graphite::Deps/Python::Pip[django-tagging==0.3.1]/Exec[pip_install_django-tagging==0.3.1]/returns: executed successfully
notice: /Stage[main]/Graphite::Deps/Python::Pip[gunicorn]/Exec[pip_install_gunicorn]/returns: executed successfully
notice: /Stage[main]/Graphite::Deps/Python::Pip[simplejson==2.1.6]/Exec[pip_install_simplejson==2.1.6]/returns: executed successfully
notice: /Stage[main]/Graphite::Deps/File[/var/lib/graphite/lib/python2.7/site-packages/cairo]/ensure: created
notice: /Stage[main]/Graphite::Install/Python::Pip[graphite-web==0.9.12]/Exec[pip_install_graphite-web==0.9.12]/returns: executed successfully
notice: /Stage[main]/Graphite::Install/Python::Pip[whisper==0.9.12]/Exec[pip_install_whisper==0.9.12]/returns: executed successfully
notice: /Stage[main]/Graphite::Install/Python::Pip[carbon==0.9.12]/Exec[pip_install_carbon==0.9.12]/returns: executed successfully
notice: /Stage[main]/Graphite::Config/File[/etc/init.d/carbon-aggregator]/ensure: created
err: /Stage[main]/Graphite::Config/File[/var/lib/graphite/conf/storage-aggregation.conf]/ensure: change from absent to file failed: Could not set 'file on ensure: No such file or directory - /var/lib/graphite/conf/storage-aggregation.conf.puppettmp_5202 at /etc/puppet/modules/graphite/manifests/config.pp:90
err: /Stage[main]/Graphite::Config/File[/var/lib/graphite/conf/storage-schemas.conf]/ensure: change from absent to file failed: Could not set 'file on ensure: No such file or directory - /var/lib/graphite/conf/storage-schemas.conf.puppettmp_2641 at /etc/puppet/modules/graphite/manifests/config.pp:96
notice: /Stage[main]/Graphite::Config/File[/etc/init/carbon-aggregator.conf]/ensure: created
notice: /Stage[main]/Graphite::Config/File[/etc/init/graphite-web.conf]/ensure: created
err: /Stage[main]/Graphite::Config/File[/var/lib/graphite/storage/log/webapp/]/ensure: change from absent to directory failed: Cannot create /var/lib/graphite/storage/log/webapp; parent directory /var/lib/graphite/storage/log does not exist
err: /Stage[main]/Graphite::Config/File[/var/lib/graphite/conf/carbon.conf]/ensure: change from absent to present failed: Could not set 'present on ensure: No such file or directory - /var/lib/graphite/conf/carbon.conf.puppettmp_274 at /etc/puppet/modules/graphite/manifests/config.pp:78
err: /Stage[main]/Graphite::Config/File[/var/lib/graphite/webapp/graphite/local_settings.py]/ensure: change from absent to file failed: Could not set 'file on ensure: No such file or directory - /var/lib/graphite/webapp/graphite/local_settings.py.puppettmp_6721 at /etc/puppet/modules/graphite/manifests/config.pp:133
err: /Stage[main]/Graphite::Config/File[/var/lib/graphite/webapp/graphite/initial_data.json]/ensure: change from absent to present failed: Could not set 'present on ensure: No such file or directory - /var/lib/graphite/webapp/graphite/initial_data.json.puppettmp_1812 at /etc/puppet/modules/graphite/manifests/config.pp:115
notice: /Stage[main]/Graphite::Config/Exec[init-db]: Dependency File[/var/lib/graphite/webapp/graphite/initial_data.json] has failures: true
warning: /Stage[main]/Graphite::Config/Exec[init-db]: Skipping because of failed dependencies
notice: /Stage[main]/Graphite::Config/File[/var/lib/graphite/storage/graphite.db]: Dependency File[/var/lib/graphite/webapp/graphite/initial_data.json] has failures: true
warning: /Stage[main]/Graphite::Config/File[/var/lib/graphite/storage/graphite.db]: Skipping because of failed dependencies
notice: /Stage[main]/Graphite::Config/File[/etc/init.d/graphite-web]/ensure: created
notice: /Stage[main]/Graphite::Config/File[/etc/init.d/carbon-cache]/ensure: created
notice: /Stage[main]/Graphite::Config/File[/etc/init/carbon-cache.conf]/ensure: created
info: Class[Graphite::Config]: Scheduling refresh of Class[Graphite::Service]
info: Class[Graphite::Service]: Scheduling refresh of Service[carbon-aggregator]
info: Class[Graphite::Service]: Scheduling refresh of Service[carbon-cache]
info: Class[Graphite::Service]: Scheduling refresh of Service[graphite-web]
notice: /Stage[main]/Graphite::Service/Service[carbon-aggregator]: Dependency File[/var/lib/graphite/webapp/graphite/initial_data.json] has failures: true
notice: /Stage[main]/Graphite::Service/Service[carbon-aggregator]: Dependency File[/var/lib/graphite/conf/storage-aggregation.conf] has failures: true
notice: /Stage[main]/Graphite::Service/Service[carbon-aggregator]: Dependency File[/var/lib/graphite/storage/log/webapp/] has failures: true
notice: /Stage[main]/Graphite::Service/Service[carbon-aggregator]: Dependency File[/var/lib/graphite/webapp/graphite/local_settings.py] has failures: true
notice: /Stage[main]/Graphite::Service/Service[carbon-aggregator]: Dependency File[/var/lib/graphite/conf/storage-schemas.conf] has failures: true
notice: /Stage[main]/Graphite::Service/Service[carbon-aggregator]: Dependency File[/var/lib/graphite/conf/carbon.conf] has failures: true
warning: /Stage[main]/Graphite::Service/Service[carbon-aggregator]: Skipping because of failed dependencies
notice: /Stage[main]/Graphite::Service/Service[carbon-aggregator]: Triggered 'refresh' from 1 events
notice: /Stage[main]/Graphite::Service/Service[carbon-cache]: Dependency File[/var/lib/graphite/webapp/graphite/initial_data.json] has failures: true
notice: /Stage[main]/Graphite::Service/Service[carbon-cache]: Dependency File[/var/lib/graphite/conf/storage-aggregation.conf] has failures: true
notice: /Stage[main]/Graphite::Service/Service[carbon-cache]: Dependency File[/var/lib/graphite/storage/log/webapp/] has failures: true
notice: /Stage[main]/Graphite::Service/Service[carbon-cache]: Dependency File[/var/lib/graphite/webapp/graphite/local_settings.py] has failures: true
notice: /Stage[main]/Graphite::Service/Service[carbon-cache]: Dependency File[/var/lib/graphite/conf/storage-schemas.conf] has failures: true
notice: /Stage[main]/Graphite::Service/Service[carbon-cache]: Dependency File[/var/lib/graphite/conf/carbon.conf] has failures: true
warning: /Stage[main]/Graphite::Service/Service[carbon-cache]: Skipping because of failed dependencies
notice: /Stage[main]/Graphite::Service/Service[carbon-cache]: Triggered 'refresh' from 1 events
notice: /Stage[main]/Graphite::Service/Service[graphite-web]: Dependency File[/var/lib/graphite/webapp/graphite/initial_data.json] has failures: true
notice: /Stage[main]/Graphite::Service/Service[graphite-web]: Dependency File[/var/lib/graphite/conf/storage-aggregation.conf] has failures: true
notice: /Stage[main]/Graphite::Service/Service[graphite-web]: Dependency File[/var/lib/graphite/storage/log/webapp/] has failures: true
notice: /Stage[main]/Graphite::Service/Service[graphite-web]: Dependency File[/var/lib/graphite/webapp/graphite/local_settings.py] has failures: true
notice: /Stage[main]/Graphite::Service/Service[graphite-web]: Dependency File[/var/lib/graphite/conf/storage-schemas.conf] has failures: true
notice: /Stage[main]/Graphite::Service/Service[graphite-web]: Dependency File[/var/lib/graphite/conf/carbon.conf] has failures: true
warning: /Stage[main]/Graphite::Service/Service[graphite-web]: Skipping because of failed dependencies
notice: /Stage[main]/Graphite::Service/Service[graphite-web]: Triggered 'refresh' from 1 events
info: Creating state file /var/lib/puppet/state/state.yaml
notice: Finished catalog run in 188.16 seconds

```

**Comment by deanwilson** [comment] 2016-01-29 10:24
Hi @jhoblitt,

Firstly apologies for not getting around to this issue sooner.

We've tested the vagrant image under vagrant 1.7.4 and we've been unable to reproduce the issue. We're planning on moving to Trusty in the very near future so hopefully this problem is resolved and won't return. If it does please feel free to reopen the issue and we can take another look.

**Closed by deanwilson** 2016-01-29 10:24 UTC
